export const TOGGLE_EDITOR_READ_ONLY = {
  type: 'TOGGLE_EDITOR_READ_ONLY',
};

export const TOGGLE_EDITOR_DARK_MODE = {
  type: 'TOGGLE_EDITOR_DARK_MODE',
};

export default {
  'TOGGLE_EDITOR_READ_ONLY': TOGGLE_EDITOR_READ_ONLY,
  'TOGGLE_EDITOR_DARK_MODE': TOGGLE_EDITOR_DARK_MODE,
}
